Add 256-byte polyval tests
google/hctr2 pull request #42
Opened 2022-01-04 02:34 UTC by Nathan-Huckleberry

- Add 256-byte testvectors to polyval

2022-01-04 03:36 UTC, ciphergoth requested changes

2022-01-04 03:36 UTC, ciphergoth commented on python/ciphers/polyval.py
>          for mlen in range(0, 80, 16):
I think just do `for mlen in [0, 16, 32, 48, 64, 256]:`

2022-01-04 13:51 UTC, ciphergoth approved these changes

2022-01-05 22:50 UTC, ebiggers approved these changes
In the future, please squash your commits when fixing up a previous commit in the same pull request -- thanks!

2022-01-05 22:50 UTC, merged